# Generated by Django 3.2.6 on 2021-08-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio_cnb', '0002_alter_request_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Jugando', 'Jugando'), ('Campeonato Finalizado', 'Campeonato Finalizado'), ('Liberado', 'Liberado')], default='Pendiente', max_length=50, null=True),
        ),
    ]
